<?php
if (! defined('BASEPATH'))
    exit('No direct script access allowed');
    
    /*
 * |--------------------------------------------------------------------------
 * | Base Site URL
 * |--------------------------------------------------------------------------
 * |
 * | URL to your CodeIgniter root. Typically this will be your base URL,
 * | WITH a trailing slash:
 * |
 * | http://example.com/
 * |
 * | If this is not set then CodeIgniter will guess the protocol, domain and
 * | path to your installation.
 * |
 */
$config['base_url'] = '';
$config['time_zone'] = date_default_timezone_set('Asia/shanghai');
/*
 * |--------------------------------------------------------------------------
 * | Index File
 * |--------------------------------------------------------------------------
 * |
 * | Typically this will be your index.php file, unless you've renamed it to
 * | something else. If you are using mod_rewrite to remove the page set this
 * | variable so that it is blank.
 * |
 */
$config['index_page'] = 'index.php';

/*
 * |--------------------------------------------------------------------------
 * | URI PROTOCOL
 * |--------------------------------------------------------------------------
 * |
 * | This item determines which server global should be used to retrieve the
 * | URI string. The default setting of 'AUTO' works for most servers.
 * | If your links do not seem to work, try one of the other delicious flavors:
 * |
 * | 'AUTO' Default - auto detects
 * | 'PATH_INFO' Uses the PATH_INFO
 * | 'QUERY_STRING' Uses the QUERY_STRING
 * | 'REQUEST_URI' Uses the REQUEST_URI
 * | 'ORIG_PATH_INFO' Uses the ORIG_PATH_INFO
 * |
 */
$config['uri_protocol'] = 'AUTO';

/*
 * |--------------------------------------------------------------------------
 * | URL suffix
 * |--------------------------------------------------------------------------
 * |
 * | This option allows you to add a suffix to all URLs generated by CodeIgniter.
 * | For more information please see the user guide:
 * |
 * | http://codeigniter.com/user_guide/general/urls.html
 */

$config['url_suffix'] = '';

/*
 * |--------------------------------------------------------------------------
 * | Default Language
 * |--------------------------------------------------------------------------
 * |
 * | This determines which set of language files should be used. Make sure
 * | there is an available translation if you intend to use something other
 * | than english.
 * |
 */
$config['language'] = 'chinese';

/*
 * |--------------------------------------------------------------------------
 * | Default Character Set
 * |--------------------------------------------------------------------------
 * |
 * | This determines which character set is used by default in various methods
 * | that require a character set to be provided.
 * |
 */
$config['charset'] = 'UTF-8';

/*
 * |--------------------------------------------------------------------------
 * | Enable/Disable System Hooks
 * |--------------------------------------------------------------------------
 * |
 * | If you would like to use the 'hooks' feature you must enable it by
 * | setting this variable to TRUE (boolean). See the user guide for details.
 * |
 */
$config['enable_hooks'] = FALSE;

/*
 * |--------------------------------------------------------------------------
 * | Class Extension Prefix
 * |--------------------------------------------------------------------------
 * |
 * | This item allows you to set the filename/classname prefix when extending
 * | native libraries. For more information please see the user guide:
 * |
 * | http://codeigniter.com/user_guide/general/core_classes.html
 * | http://codeigniter.com/user_guide/general/creating_libraries.html
 * |
 */
$config['subclass_prefix'] = 'MY_';

/*
 * |--------------------------------------------------------------------------
 * | Allowed URL Characters
 * |--------------------------------------------------------------------------
 * |
 * | This lets you specify with a regular expression which characters are permitted
 * | within your URLs. When someone tries to submit a URL with disallowed
 * | characters they will get a warning message.
 * |
 * | As a security measure you are STRONGLY encouraged to restrict URLs to
 * | as few characters as possible. By default only these are allowed: a-z 0-9~%.:_-
 * |
 * | Leave blank to allow all characters -- but only if you are insane.
 * |
 * | DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
 * |
 */
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
 * |--------------------------------------------------------------------------
 * | Enable Query Strings
 * |--------------------------------------------------------------------------
 * |
 * | By default CodeIgniter uses search-engine friendly segment based URLs:
 * | example.com/who/what/where/
 * |
 * | By default CodeIgniter enables access to the $_GET array. If for some
 * | reason you would like to disable it, set 'allow_get_array' to FALSE.
 * |
 * | You can optionally enable standard query string based URLs:
 * | example.com?who=me&what=something&where=here
 * |
 * | Options are: TRUE or FALSE (boolean)
 * |
 * | The other items let you set the query string 'words' that will
 * | invoke your controllers and its functions:
 * | example.com/index.php?c=controller&m=function
 * |
 * | Please note that some of the helpers won't work as expected when
 * | this feature is enabled, since CodeIgniter is designed primarily to
 * | use segment based URLs.
 * |
 */
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = TRUE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd'; // experimental not currently in use

/*
 * |--------------------------------------------------------------------------
 * | Error Logging Threshold
 * |--------------------------------------------------------------------------
 * |
 * | If you have enabled error logging, you can set an error threshold to
 * | determine what gets logged. Threshold options are:
 * | You can enable error logging by setting a threshold over zero. The
 * | threshold determines what gets logged. Threshold options are:
 * |
 * | 0 = Disables logging, Error logging TURNED OFF
 * | 1 = Error Messages (including PHP errors)
 * | 2 = Debug Messages
 * | 3 = Informational Messages
 * | 4 = All Messages
 * |
 * | For a live site you'll usually only enable Errors (1) to be logged otherwise
 * | your log files will fill up very fast.
 * |
 */
$config['log_threshold'] = 0;

/*
 * |--------------------------------------------------------------------------
 * | Error Logging Directory Path
 * |--------------------------------------------------------------------------
 * |
 * | Leave this BLANK unless you would like to set something other than the default
 * | application/logs/ folder. Use a full server path with trailing slash.
 * |
 */
$config['log_path'] = '';

/*
 * |--------------------------------------------------------------------------
 * | Date Format for Logs
 * |--------------------------------------------------------------------------
 * |
 * | Each item that is logged has an associated date. You can use PHP date
 * | codes to set your own date formatting
 * |
 */
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
 * |--------------------------------------------------------------------------
 * | Cache Directory Path
 * |--------------------------------------------------------------------------
 * |
 * | Leave this BLANK unless you would like to set something other than the default
 * | system/cache/ folder. Use a full server path with trailing slash.
 * |
 */
$config['cache_path'] = '';

/*
 * |--------------------------------------------------------------------------
 * | Encryption Key
 * |--------------------------------------------------------------------------
 * |
 * | If you use the Encryption class or the Session class you
 * | MUST set an encryption key. See the user guide for info.
 * |
 */
$config['encryption_key'] = 'sdfx!lkjdfson';

/*
 * |--------------------------------------------------------------------------
 * | Session Variables
 * |--------------------------------------------------------------------------
 * |
 * | 'sess_cookie_name' = the name you want for the cookie
 * | 'sess_expiration' = the number of SECONDS you want the session to last.
 * | by default sessions last 7200 seconds (two hours). Set to zero for no expiration.
 * | 'sess_expire_on_close' = Whether to cause the session to expire automatically
 * | when the browser window is closed
 * | 'sess_encrypt_cookie' = Whether to encrypt the cookie
 * | 'sess_use_database' = Whether to save the session data to a database
 * | 'sess_table_name' = The name of the session database table
 * | 'sess_match_ip' = Whether to match the user's IP address when reading the session data
 * | 'sess_match_useragent' = Whether to match the User Agent when reading the session data
 * | 'sess_time_to_update' = how many seconds between CI refreshing Session Information
 * |
 */
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_expire_on_close'] = FALSE;
$config['sess_encrypt_cookie'] = FALSE;
$config['sess_use_database'] = FALSE;
$config['sess_table_name'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_match_useragent'] = TRUE;
$config['sess_time_to_update'] = 300;

/*
 * |--------------------------------------------------------------------------
 * | Cookie Related Variables
 * |--------------------------------------------------------------------------
 * |
 * | 'cookie_prefix' = Set a prefix if you need to avoid collisions
 * | 'cookie_domain' = Set to .your-domain.com for site-wide cookies
 * | 'cookie_path' = Typically will be a forward slash
 * | 'cookie_secure' = Cookies will only be set if a secure HTTPS connection exists.
 * |
 */
$config['cookie_prefix'] = "";
$config['cookie_domain'] = "";
$config['cookie_path'] = "/";
$config['cookie_secure'] = FALSE;

/*
 * |--------------------------------------------------------------------------
 * | Global XSS Filtering
 * |--------------------------------------------------------------------------
 * |
 * | Determines whether the XSS filter is always active when GET, POST or
 * | COOKIE data is encountered
 * |
 */
$config['global_xss_filtering'] = FALSE;

/*
 * |--------------------------------------------------------------------------
 * | Cross Site Request Forgery
 * |--------------------------------------------------------------------------
 * | Enables a CSRF cookie token to be set. When set to TRUE, token will be
 * | checked on a submitted form. If you are accepting user data, it is strongly
 * | recommended CSRF protection be enabled.
 * |
 * | 'csrf_token_name' = The token name
 * | 'csrf_cookie_name' = The cookie name
 * | 'csrf_expire' = The number in seconds the token should expire.
 */
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
 * |--------------------------------------------------------------------------
 * | Output Compression
 * |--------------------------------------------------------------------------
 * |
 * | Enables Gzip output compression for faster page loads. When enabled,
 * | the output class will test whether your server supports Gzip.
 * | Even if it does, however, not all browsers support compression
 * | so enable only if you are reasonably sure your visitors can handle it.
 * |
 * | VERY IMPORTANT: If you are getting a blank page when compression is enabled it
 * | means you are prematurely outputting something to your browser. It could
 * | even be a line of whitespace at the end of one of your scripts. For
 * | compression to work, nothing can be sent before the output buffer is called
 * | by the output class. Do not 'echo' any values with compression enabled.
 * |
 */
$config['compress_output'] = FALSE;

/*
 * |--------------------------------------------------------------------------
 * | Master Time Reference
 * |--------------------------------------------------------------------------
 * |
 * | Options are 'local' or 'gmt'. This pref tells the system whether to use
 * | your server's local time as the master 'now' reference, or convert it to
 * | GMT. See the 'date helper' page of the user guide for information
 * | regarding date handling.
 * |
 */
$config['time_reference'] = 'local';

/*
 * |--------------------------------------------------------------------------
 * | Rewrite PHP Short Tags
 * |--------------------------------------------------------------------------
 * |
 * | If your PHP installation does not have short tag support enabled CI
 * | can rewrite the tags on-the-fly, enabling you to utilize that syntax
 * | in your view files. Options are TRUE or FALSE (boolean)
 * |
 */
$config['rewrite_short_tags'] = FALSE;

/*
 * |--------------------------------------------------------------------------
 * | Reverse Proxy IPs
 * |--------------------------------------------------------------------------
 * |
 * | If your server is behind a reverse proxy, you must whitelist the proxy IP
 * | addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
 * | header in order to properly identify the visitor's IP address.
 * | Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
 * |
 */
$config['proxy_ips'] = '';

//路径配置
//文件路径
$db_prefix = 'jcjr';
if ($_SERVER['SERVER_NAME'] == 'api.car.com') {
    define('STATIC_HOST','http://api.car.com');
    $db_prefix = 'jcjr_db';
} else if ($_SERVER['SERVER_NAME'] == 'apitest.ifcar99.com') {
    define('STATIC_HOST','http://apitest.ifcar99.com');
    $db_prefix = 'jcjr_db';
} else if ($_SERVER['SERVER_NAME'] == 'api.ifcar99.com') {
    define('STATIC_HOST','http://static01.ifcar99.com');
    $db_prefix = 'GtYLSlBK';
} else if ($_SERVER['SERVER_NAME'] == 'api_lsk.com') {
    define('STATIC_HOST','http://api_lsk.com');
    $db_prefix = 'jcjr_db';
}else if ($_SERVER['SERVER_NAME'] == '122.224.68.82') {
    define('STATIC_HOST','http://api_lsk.com');
    $db_prefix = 'jcjr_db';
} 
else {
    define('STATIC_HOST','http://api.car.com');
    $db_prefix = 'jcjr_db';
}


if ($_SERVER['SERVER_NAME'] == 'apitest.ifcar99.com' || $_SERVER['SERVER_NAME'] == 'test.ifcar99.com') {
    define('WECHAT_HOST','http://test.ifcar99.com');
} else if ($_SERVER['SERVER_NAME'] == 'api.ifcar99.com' || $_SERVER['SERVER_NAME'] == 'www.ifcar99.com') {
    define('WECHAT_HOST','https://www.ifcar99.com');
}

//定义数据库表名
define('TABLE_API2_CATEGORY', 'api2_category'); // 接口分类表
define('TABLE_API2_METHOD', 'api2_method'); // 接口名称表
define('TABLE_API2_FIELD', 'api2_field'); // 接口 输入 输出(对象) 字段
define('TABLE_API2_LOG', 'api2_log');
define('TABLE_TOKEN', 'api2_token');
define('TABLE_USER', $db_prefix .'.yyd_users');
define('TABLE_USER_INFO', $db_prefix .'.yyd_users_info');
define('TABLE_USER_REALNAME', $db_prefix .'.yyd_approve_realname');
define('TABLE_USER_FRIENDS', $db_prefix .'.yyd_users_friends');//好友表
define('TABLE_USER_FRIENDS_INVITE', $db_prefix .'.yyd_users_friends_invite');//邀请人表
define('TABLE_USER_THIRD', 'v1_user_third');//渠道用户表
define('TABLE_ACCOUNT', $db_prefix .'.yyd_account');
define('TABLE_ACCOUNT_USERS', $db_prefix .'.yyd_account_users');
define('TABLE_ACCOUNT_LOG', $db_prefix .'.yyd_account_log');
define('TABLE_ACCOUNT_RECHARGE', $db_prefix .'.yyd_account_recharge');//充值记录
define('TABLE_PAYMENT_BANK', 'v1_payment_bank');//充值方式对应支持的银行
define('TABLE_GOODS', 'v1_goods');
define('TABLE_GOODS_CATEGORY', 'v1_goods_category');
define('TABLE_ORDER', 'v1_order');
define('TABLE_ORDER_GOODS', 'v1_order_goods');
define('TABLE_GOODS_USER_BUY', 'v1_goods_user_buy');
define('TABLE_GOODS_ZONE', 'v1_goods_zone');
define('TABLE_GOODS_ZONE_ITEM', 'v1_goods_zone_item');
define('TABLE_USER_ADDRESS', 'v1_user_address');
define('TABLE_AREA', $db_prefix .'.yyd_areas');
define('TABLE_CREDIT', $db_prefix .'.yyd_credit');
define('TABLE_CREDIT_TYPE', $db_prefix .'.yyd_credit_type');
define('TABLE_CREDIT_LOG', $db_prefix .'.yyd_credit_log');
define('TABLE_CREDIT_CLASS', $db_prefix .'.yyd_credit_class');
define('TABLE_BOUNS', $db_prefix .'.yyd_hbag');
define('TABLE_BOUNS_USER', $db_prefix .'.yyd_hbuser');
define('TABLE_BOUNS_CONTROL', $db_prefix .'.yyd_hbcontrol');
define('TABLE_COUPON', 'v1_coupon');
define('TABLE_COUPON_USER', 'v1_coupon_user');
define('TABLE_COUPON_USER_USE', 'v1_coupon_user_use');
define('TABLE_EXPERIENCE', 'v1_experience');
define('TABLE_EXPERIENCE_USER', 'v1_experience_user');
define('TABLE_EXPERIENCE_ACCOUNT', 'v1_experience_account');
define('TABLE_EXPERIENCE_LOG', 'v1_experience_log');
define('TABLE_PRIZE', 'v1_prize');// 奖品表
define('TABLE_PRIZE_CHANCE', 'v1_prize_chance');// 奖品机会表
define('TABLE_PRIZE_RANGE', 'v1_prize_range');// 奖品机会表
define('TABLE_PHONE_RECHARGE_LOG', $db_prefix .'.yyd_llcz');//话费充值记录
define('TABLE_QUEUE_PHONE_RECHARGE', 'v1_queue_phone_recharge');//话费充值队列
define('TABLE_QUEUE_BORROW_TENDER', 'v1_queue_borrow_tender');//项目投资队列
define('TABLE_QUEUE_BORROW', 'v1_queue_borrow');//项目队列
define('TABLE_QUEUE_SMS', 'v1_queue_sms');//短信队列
define('TABLE_QUEUE_RECHARGE', 'v1_queue_recharge');//充值安存数据同步队列
define('TABLE_SCRIPT', 'v1_script');//脚本
define('TABLE_SCRIPT_VALUES', 'v1_script_values');//脚本变量
define('TABLE_BUSINESS_CITY', 'v1_business_city');//业务城市
define('TABLE_BUSINESS_CITY_LOG', 'v1_business_city_log');//业务城市日常数据
define('TABLE_WINNING', 'v1_winning');// 抽奖记录表
define('TABLE_BORROW', $db_prefix .'.yyd_borrow');//投资表
define('TABLE_BORROW_TENDER', $db_prefix .'.yyd_borrow_tender');//用户投资记录表
define('TABLE_BORROW_REPAY', $db_prefix .'.yyd_borrow_repay');//项目回款时间记录表
define('TABLE_BORROW_RECOVER', $db_prefix .'.yyd_borrow_recover');//项目投资人回款记录表
define('TABLE_INVEST_ACCOUNT_STAT_DAILY', 'v1_invest_account_stat_daily');//司账户日余额汇总
define('TABLE_ACTIVITY', 'v1_activity');//司账户日余额汇总
define('TABLE_COUPON_ACTIVITY_161124', $db_prefix .'.yyd_invite_coupon');//加息券活动161124
define('TABLE_BALANCE_ACCOUNT', 'v1_balance_account');//用户账户对账
define('TABLE_ACCOUNT', $db_prefix .'.yyd_account');//用户投资记录表
define('TABLE_BALANCE_LOG', 'v1_balance_log');//流水对账
define('TABLE_BALANCE_BORROW', 'v1_balance_borrow');//标的对账
define('TABLE_BALANCE_ERROR', 'v1_balance_error');//异常报警
define('TABLE_CASH', $db_prefix .'.yyd_account_cash');//提现表
define('TABLE_ACCOUNT_USERS_BANK', $db_prefix .'.yyd_account_users_bank');//用户银行卡表
define('TABLE_QUEUE_FLOW_RECHARGE', 'v1_queue_flow_recharge');//话费充值队列
define('TABLE_ACCOUNT_BANK', $db_prefix .'.yyd_account_bank');//银行表
define('TABLE_USERBANK_MODIFY_LOG', 'v1_userbank_modify_log');//用户银行卡修改记录表
define('TABLE_USER_LOG', $db_prefix .'.yyd_users_log');//用户操作记录
//权限相关表
define('TABLE_ROLE', 'v1_role');//角色表
define('TABLE_USER_ROLE', 'v1_user_role');//用户角色
define('TABLE_ROLE_PRIVILEGE', 'v1_role_privilege');//角色对应权限
define('TABLE_FILE', 'v1_file');//文件表
//错误相关表
define('TABLE_ERRORS', 'v1_errors');//角色表
//融资平台
define('TABLE_FINANCE_ACCOUNT', 'v1_finance_account');//融资账户
define('TABLE_FINANCE_ACCOUNT_HISTORY', 'v1_finance_account_history');//融资账户历史
define('TABLE_FINANCE_ACCOUNT_SUB', 'v1_finance_account_sub');//融资子账户
define('TABLE_FINANCE_ACCOUNT_SUB_HISTORY', 'v1_finance_account_sub_history');//融资子账户历史
define('TABLE_FINANCE_BILL', 'v1_finance_bill');//融资单
define('TABLE_FINANCE_BILL_HISTORY', 'v1_finance_bill_history');//融资单历史
define('TABLE_FINANCE_USER_ACTION', 'v1_finance_user_action');//融资单操作记录
//文章
define('TABLE_ARTICLE', 'v1_article');//文章表
define('TABLE_OLD_ARTICLE', $db_prefix .'.yyd_articles');//原文章表
//任务表
define('TABLE_TASK', 'v1_task');//
//银行卡
define('TABLE_BANK_CARD', 'v1_bank_card');
//
//2017-3-8三八节活动奖品
define('TABLE_ACTIVITY_2017_3_2', 'v1_activity_2017_3_2');//三八节活动表
//用户操作日志
define('TABLE_USERS_LOG', $db_prefix.'.yyd_users_log');// 用户操作日志表

define('TABLE_FEEDBACK', 'v1_feedback');//意见反馈表

define('TABLE_QUEUE_WECHAT_MSG', 'v1_queue_wechat_msg');//微信公众号模板信息队列

define('TABLE_USERBANK_DELETE_LOG', 'v1_userbank_delete_log');// 银行卡删除记录表
define('TABLE_USERBANK_MODIFY_LOG', 'v1_userbank_modify_log');// 银行卡修改记录表

define('TABLE_WECHAT_MP', 'v1_wechat_mp');//微信公众号信息表

//风控审核
define('TABLE_RISK_STATS', 'v1_risk_stats');//风控审核统计

//五一活动红包表
define('TABLE_ACTIVITY_4_25', $db_prefix.'.yyd_activity_4_25');

//存管
define('TABLE_BA_ACTIONS', 'v1_ba_actions');//存管操作记录表
define('TABLE_BA_BORROW_ID', 'v1_ba_borrow_id');//存管操作记录表
define('TABLE_BA_RECHARGE', 'v1_ba_recharge');//存管充值记录表
define('TABLE_BA_TENDER_NA', 'v1_ba_tender_na');//存管投标记录表
define('TABLE_ACCOUNT_OLD', $db_prefix .'.yyd_account_old');//原有账户表

//2.0改版
define('TABLE_BANNER', 'v1_banner');//首页banner
define('TABLE_RISK_TEST', 'v1_risk_test');//首页banner

//破十亿祝福活动
define('TABLE_ACTIVITY_WISH', 'v1_activity_wish');

//站内信
define('TABLE_MESSAGE', 'v1_message');
define('TABLE_MESSAGE_TEXT', 'v1_message_text');
define('TABLE_MESSAGE_USER', 'v1_message_user');

//公告
define('TABLE_NOTICE', $db_prefix .'.yyd_notice');

//常用参数
define('STATUS_HAS_DELETE',1);//is_delete 已删除
define('STATUS_NOT_DELETE',2);//is_delete 未删除

//错误码分类
// 1** 接口级别错误，3位数
// 1*** 资源级别错误，4位数
// 2*** - 9*** 业务级别错误
//系统错误信息码表，命名规则错误码为ERR_ + 错误名称英文大写 + _NO ，错误信息为ERR_ + 错误名称英文大写 + _MSG
define('ERR_API_NOT_EXISTS_NO',100);
define('ERR_API_NOT_EXISTS_MSG','接口不存在');

define('ERR_SUCCESS_NO',200);
define('ERR_SUCCESS_MSG','请求成功');

define('ERR_FAILED_NO',400);
define('ERR_FAILED_MSG','请求失败');

define('ERR_TOKEN_NOT_EXISTS_NO',401);
define('ERR_TOKEN_NOT_EXISTS_MSG','登录已失效，请重新登录');

define('ERR_TOKEN_EXPIRE_NO',402);
define('ERR_TOKEN_EXPIRE_MSG','登录已过期，请重新登录');

define('ERR_TOKEN_DISABLED_NO',409);
define('ERR_TOKEN_DISABLED_MSG','TOKEN已失效');

define('ERR_FILED_NECESSARY_NO',403);
define('ERR_FILED_NECESSARY_MSG','参数不能为空');

define('ERR_PERMISSION_DENIED_NO',404);
define('ERR_PERMISSION_DENIED_MSG','没有权限');

define('ERR_ITEM_NOT_EXISTS_NO',405);
define('ERR_ITEM_NOT_EXISTS_MSG','相关信息不存在');

define('ERR_ITEM_REPEAT_NO',406);
define('ERR_ITEM_REPEAT_MSG','相关信息重复');

define('ERR_WRONG_FORMAT_NO',407);
define('ERR_WRONG_FORMAT_MSG','格式错误');

define('ERR_USER_ACCOUNT_DISABLE_NO',408);
define('ERR_USER_ACCOUNT_DISABLE_MSG','账号已注销');

define('ERR_ACTION_REPEAT_NO',410);
define('ERR_ACTION_REPEAT_MSG','请勿重复操作');

define('ERR_TRY_AGAIN_NO',411);
define('ERR_TRY_AGAIN_MSG','请重试');

//用户相关
define('ERR_LOGINNAME_EXISTS_NO',2001);
define('ERR_LOGINNAME_EXISTS_MSG','用户名已存在');

define('ERR_LOGINNAME_NOT_EXISTS_NO',2002);
define('ERR_LOGINNAME_NOT_EXISTS_MSG','用户名不存在');

define('ERR_WRONG_PASSWORD_NO',2003);
define('ERR_WRONG_PASSWORD_MSG','密码错误');

define('ERR_NOT_CHINESE_NAME_NO',2010);
define('ERR_NOT_CHINESE_NAME_MSG','姓名格式有误');

define('ERR_NOT_PHONE_NUM_NO',2011);
define('ERR_NOT_PHONE_NUM_MSG','手机号码格式有误');

define('ERR_OVER_ADDRESS_LIMIT_NO',2012);
define('ERR_OVER_ADDRESS_LIMIT_MSG','超出用户地址数量限制');

define('ERR_WRONG_PAY_PASSWORD_NO',2013);
define('ERR_WRONG_PAY_PASSWORD_MSG','交易密码错误');

define('ERR_PAY_PASSWORD_NOT_SET_NO',2014);
define('ERR_PAY_PASSWORD_NOT_SET_MSG','交易密码未设置');

define('ERR_CONFIRM_PASSWORD_ERROR_NO',2015);
define('ERR_CONFIRM_PASSWORD_ERROR_MSG','两次输入密码不一致');

define('ERR_INVITE_ID_FORMAT_ERROR_NO',2016);
define('ERR_INVITE_ID_FORMAT_ERROR_MSG','邀请码格式错误');

define('ERR_PHONE_NOT_EXISTS_NO',2017);
define('ERR_PHONE_NOT_EXISTS_MSG','手机号码未填写');

define('ERR_PASSWORD_NOT_EXISTS_NO',2018);
define('ERR_PASSWORD_NOT_EXISTS_MSG','密码未填写');

define('ERR_CONFIRM_PASSWORD_NOT_EXISTS_NO',2019);
define('ERR_CONFIRM_PASSWORD_NOT_EXISTS_MSG','确认密码未填写');

define('ERR_INVITE_ID_NOT_EXISTS_NO',2020);
define('ERR_INVITE_ID_NOT_EXISTS_MSG','邀请码不存在');

define('ERR_MOBILE_CODE_ERROR_NO',2021);
define('ERR_MOBILE_CODE_ERROR_MSG','验证码错误');

define('ERR_PHONE_ERROR_NO',2022);
define('ERR_PHONE_ERROR_MSG','验证手机号错误');

define('ERR_REPEAT_SIGN_NO',2050);
define('ERR_REPEAT_SIGN_MSG','重复签到');

define('ERR_PASSWORD_LENGTH_NO',2051);
define('ERR_PASSWORD_LENGTH_MSG','密码的长度在6到15位之间');


//商品相关
define('ERR_GOODS_NOT_EXISTS_NO',3001);
define('ERR_GOODS_NOT_EXISTS_MSG','商品不存在');

define('ERR_GOODS_OFF_NO',3002);
define('ERR_GOODS_OFF_MSG','商品下架');

define('ERR_GOODS_TIME_LIMIT_BEGIN_NO',3003);
define('ERR_GOODS_TIME_LIMIT_BEGIN_MSG','还未到商品开放购买时间');

define('ERR_GOODS_TIME_LIMIT_END_NO',3004);
define('ERR_GOODS_TIME_LIMIT_END_MSG','已超过商品截止购买时间');

//订单相关
define('ERR_ORDER_NOT_EXISTS_NO',4001);
define('ERR_ORDER_NOT_EXISTS_MSG','订单不存在');

define('ERR_CREDIT_NOT_ENOUGH_NO',4002);
define('ERR_CREDIT_NOT_ENOUGH_MSG','余额不足');

define('ERR_MALL_OFF_NO',4003);
define('ERR_MALL_OFF_MSG','积分商城功能关闭');

define('ERR_OUT_OF_STOCK_NO',4004);
define('ERR_OUT_OF_STOCK_MSG','商品缺货');

define('ERR_BEYOND_THE_LIMIT_NO',4005);
define('ERR_BEYOND_THE_LIMIT_MSG','超出单人商品购买数量');

define('ERR_ORDER_EMPTY_NO',4006);
define('ERR_ORDER_EMPTY_MSG','订单商品不能为空');

define('ERR_NOT_ALLOWED_CATEGORY_NO',4007);
define('ERR_NOT_ALLOWED_CATEGORY_MSG','不支持的商品类别');

define('ERR_ORDER_GOODS_NUM_EMPTY_NO',4008);
define('ERR_ORDER_GOODS_NUM_EMPTY_MSG','订单商品数量不能为0');

define('ERR_AREA_NOT_MATCH_NO',4050);
define('ERR_AREA_NOT_MATCH_MSG','省份城市等地区信息不匹配');

//文件相关
define('ERR_FILE_FORMAT_ERROR_NO',5001);
define('ERR_FILE_FORMAT_ERROR_MSG','文件格式错误');

define('ERR_REQUIRE_GD_NO',5006);
define('ERR_REQUIRE_GD_MSG','需要GD库支持');

//话费充值相关
define('ERR_BEYOND_USER_MONTH_LIMIT_NO',6001);
define('ERR_BEYOND_USER_MONTH_LIMIT_MSG','超出每月限额');

define('ERR_BEYOND_PER_ORDER_LIMIT_NO',6002);
define('ERR_BEYOND_PER_ORDER_LIMIT_MSG','超出单订单购买数量限制');

//奖品相关
define('ERR_PRIZE_NOT_EXISTS_NO',7004);
define('ERR_PRIZE_NOT_EXISTS_MSG','奖品不存在');

define('ERR_PRIZE_CHANCE_NOT_ENOUGH_NO',7001);
define('ERR_PRIZE_CHANCE_NOT_ENOUGH_MSG','剩余抽奖机会不足');

define('ERR_PRIZE_CREDIT_NOT_ENOUGH_NO',7002);
define('ERR_PRIZE_CREDIT_NOT_ENOUGH_MSG','剩余抽奖积分不足');

define('ERR_PRIZE_NOT_ENOUGH_NO',7003);
define('ERR_PRIZE_NOT_ENOUGH_MSG','奖品库存不足');

define('ERR_PRIZE_NOT_EXISTS_NO',7004);
define('ERR_PRIZE_NOT_EXISTS_MSG','奖品不存在');

define('ERR_PRIZE_IID_IS_NULL_NO',7005);
define('ERR_PRIZE_IID_IS_NULL_MSG','商品ID不能为0');

define('ERR_PRIZE_HAS_SENT_NO',7006);
define('ERR_PRIZE_HAS_SENT_MSG','奖品已发放');

define('ERR_PRIZE_FAILED_TO_SEND_NO',7007);
define('ERR_PRIZE_FAILED_TO_SEND_MSG','奖品发放失败');

//活动相关
define('ERR_ACTIVITY_NOT_START_NO',8001);
define('ERR_ACTIVITY_NOT_START_MSG','活动尚未开放');

define('ERR_ACTIVITY_END_NO',8002);
define('ERR_ACTIVITY_END_MSG','活动已结束');

//加息券相关
define('ERR_COUPON_HAS_SENT_NO',9001);
define('ERR_COUPON_HAS_SENT_MSG','加息券重复发放');

define('ERR_COUPON_NO_USE_TIMES_NO',9002);
define('ERR_COUPON_NO_USE_TIMES_MSG','加息券没有可用次数');

define('ERR_COUPON_ON_TIME_LIMIT_NO',9003);
define('ERR_COUPON_ON_TIME_LIMIT_MSG','加息券还未到可用时间');

define('ERR_COUPON_OFF_TIME_LIMIT_NO',9004);
define('ERR_COUPON_OFF_TIME_LIMIT_MSG','加息券已超过可用时间');

define('ERR_COUPON_EXPIRE_TIME_LIMIT_NO',9005);
define('ERR_COUPON_EXPIRE_TIME_LIMIT_MSG','加息券已过期');

define('ERR_COUPON_USED_NO',9006);
define('ERR_COUPON_USED_MSG','加息券已使用');

define('ERR_COUPON_CLOSED_NO',9007);
define('ERR_COUPON_CLOSED_MSG','加息券已关闭');

define('ERR_COUPON_OUT_OF_STORE_NO',9008);
define('ERR_COUPON_OUT_OF_STORE_MSG','加息券没有库存');

define('ERR_COUPON_NOT_MATCH_OWNER_NO',9009);
define('ERR_COUPON_NOT_MATCH_OWNER_MSG','加息券所有者和投资用户不匹配');

define('ERR_COUPON_UPPER_MONEY_LIMIT_NO',9010);
define('ERR_COUPON_UPPER_MONEY_LIMIT_MSG','投资金额超过加息券限制');

define('ERR_COUPON_LOWER_MONEY_LIMIT_NO',9011);
define('ERR_COUPON_LOWER_MONEY_LIMIT_MSG','投资金额未达到加息券限制');

define('ERR_COUPON_DAYS_LIMIT_NO',9012);
define('ERR_COUPON_DAYS_LIMIT_MSG','加息券只能用于30天的项目！');

define('ERR_COUPON_SINGLE_BORROW_LIMIT_NO',9013);
define('ERR_COUPON_SINGLE_BORROW_LIMIT_MSG','单人满标不能使用加息券！');


//对账相关
define('ERR_BALANCE_STATUS_NO',10001);
define('ERR_BALANCE_STATUS_MSG','对账状态错误');

//红包相关
define('ERR_BOUNS_NO',10001);
define('ERR_BOUNS_MSG','红包错误信息');

define('ERR_BOUNS_REG_DISABLE_NO',10002);
define('ERR_BOUNS_REG_DISABLE_MSG','注册红包不可用');

//投资相关
define('ERR_BORROW_DISABLE_NO',11001);
define('ERR_BORROW_DISABLE_MSG','项目不可用');

define('ERR_TENDER_MONEY_FORMAT_100_NO',11002);
define('ERR_TENDER_MONEY_FORMAT_100_MSG','投资金额需为100的倍数');

define('ERR_TENDER_MONEY_LOWER_LIMIT_NO',11003);
define('ERR_TENDER_MONEY_LOWER_LIMIT_MSG','投资金额低于最低值');

define('ERR_TENDER_MONEY_UPPER_LIMIT_NO',11022);
define('ERR_TENDER_MONEY_UPPER_LIMIT_MSG','投资金额超过可投金额');

define('ERR_BORROW_AMOUNT_NOT_ENOUGH_NO',11004);
define('ERR_BORROW_AMOUNT_NOT_ENOUGH_MSG','剩余可投额度不足');

define('ERR_TENDER_TOO_FAST_NO',11005);
define('ERR_TENDER_TOO_FAST_MSG','投资频率过快');

define('ERR_TENDER_FAILED_TO_LOCK_BOUNS_NO',11006);
define('ERR_TENDER_FAILED_TO_LOCK_BOUNS_MSG','锁定红包失败');

define('ERR_TENDER_FAILED_TO_LOCK_COUPON_NO',11007);
define('ERR_TENDER_FAILED_TO_LOCK_COUPON_MSG','锁定加息券失败');

define('ERR_TENDER_BOUNS_OUT_OF_LIMIT_NO',11008);
define('ERR_TENDER_BOUNS_OUT_OF_LIMIT_MSG','红包超出使用限制');

define('ERR_TENDER_FAILED_NO',11009);
define('ERR_TENDER_FAILED_MSG','投资失败');

define('ERR_BORROW_EXPIRE_NO',11010);
define('ERR_BORROW_EXPIRE_MSG','项目过期');

define('ERR_TENDER_UPPER_MONEY_LIMIT_NO',11011);
define('ERR_TENDER_UPPER_MONEY_LIMIT_MSG','投资金额超过加息券限制');

define('ERR_TENDER_LOWER_MONEY_LIMIT_NO',11012);
define('ERR_TENDER_LOWER_MONEY_LIMIT_MSG','投资金额未达到加息券使用要求');

define('ERR_BORROW_FOR_NEW_COMMER_NO',11013);
define('ERR_BORROW_FOR_NEW_COMMER_MSG','新手专享');

define('ERR_BORROW_FOR_SINGLE_NO',11014);
define('ERR_BORROW_FOR_SINGLE_MSG','单人满标');

define('ERR_BORROW_NO_COUPON_NO',11015);
define('ERR_BORROW_NO_COUPON_MSG','该项目无法使用加息券');

define('ERR_BORROW_UPPER_MONEY_LIMIT_NO',11016);
define('ERR_BORROW_UPPER_MONEY_LIMIT_MSG','项目金额超过限制');

define('ERR_BORROW_LOWER_MONEY_LIMIT_NO',11017);
define('ERR_BORROW_LOWER_MONEY_LIMIT_MSG','项目金额低于限制');

define('ERR_BORROW_ON_TIME_LIMIT_NO',11018);
define('ERR_BORROW_ON_TIME_LIMIT_MSG','项目尚未开放投资');

define('ERR_BORROW_OFF_TIME_LIMIT_NO',11019);
define('ERR_BORROW_OFF_TIME_LIMIT_MSG','项目已停止投资');

define('ERR_BORROW_IS_NOT_EDITABLE_NO',11020);
define('ERR_BORROW_IS_NOT_EDITABLE_MSG','项目在未发布状态下才可编辑');

define('ERR_BORROW_HAS_TENDERED_NO',11021);
define('ERR_BORROW_HAS_TENDERED_MSG','项目已有用户投资');

define('ERR_BORROW_HAS_FULL_NO',11023);
define('ERR_BORROW_HAS_FULL_MSG','项目不可用');

define('ERR_BORROW_TENDER_NOT_EXISTS_NO',11024);
define('ERR_BORROW_TENDER_NOT_EXISTS_MSG','投资记录不存在');

define('ERR_RECOVER_NOT_EXISTS_NO',11025);
define('ERR_RECOVER_NOT_EXISTS_MSG','回款记录不存在');

//账户相关
define('ERR_ACCOUNT_NOT_ENOUGH_NO',12001);
define('ERR_ACCOUNT_NOT_ENOUGH_MSG','账户余额不足');

define('ERR_ACCOUNT_NOT_EXISTS_NO',12002);
define('ERR_ACCOUNT_NOT_EXISTS_MSG','资金账户不存在');

define('ERR_ACCOUNT_NOT_EMPTY_NO',12003);
define('ERR_ACCOUNT_NOT_EMPTY_MSG','账户总资产不为0');

define('ERR_ACCOUNT_EMPTY_NO',12004);
define('ERR_ACCOUNT_EMPTY_MSG','账户总资产为0');

//体验金相关
define('ERR_EXPERIENCE_DISABLE_NO',13001);
define('ERR_EXPERIENCE_DISABLE_MSG','体验金不可用');

define('ERR_EXPERIENCE_NOT_ENOUGH_NO',13002);
define('ERR_EXPERIENCE_NOT_ENOUGH_MSG','体验金余额不足');

define('ERR_EXPERIENCE_WRONG_STATUS_NO',13003);
define('ERR_EXPERIENCE_WRONG_STATUS_MSG','体验金状态错误');

define('ERR_EXPERIENCE_SHOULD_GREATER_NO',13004);
define('ERR_EXPERIENCE_SHOULD_GREATER_MSG','转出金额需要大于0.01');

define('ERR_EXPERIENCE_UPPER_MONEY_LIMIT_NO',13016);
define('ERR_EXPERIENCE_UPPER_MONEY_LIMIT_MSG','体验金累计金额超过限制');

//角色相关
define('ERR_ROLE_MEMBER_NOT_EMPTY_NO',15006);
define('ERR_ROLE_MEMBER_NOT_EMPTY_MSG','角色下用户数量大于0');

define('ERR_ROLE_USER_REPEAT_NO',15007);
define('ERR_ROLE_USER_REPEAT_MSG','用户重复添加');

//融资平台
define('ERR_MONEY_FORMAT_100_NO',16001);
define('ERR_MONEY_FORMAT_100_MSG','融资金额需为100的倍数');

define('ERR_ID_CARD_FORMAT_NO',16002);
define('ERR_ID_CARD_FORMAT_MSG','身份证号码格式错误');

define('ERR_BILL_EXPIRED_NO',16003);
define('ERR_BILL_EXPIRED_MSG','融资单已过期');

//风控
define('ERR_BILL_IS_ONLINE_NO',17001);
define('ERR_BILL_IS_ONLINE_MSG','融资需求已上线，不能再次审核');

define('ERR_BILL_VERIFY_FAILED_NO',17002);
define('ERR_BILL_VERIFY_FAILED_MSG','操作失败，请刷新重试或联系管理员！');

//微信
define('ERR_WECHAT_INFO_NOT_EXISTS_NO',18001);
define('ERR_WECHAT_INFO_NOT_EXISTS_MSG','微信信息未绑定');

define('ERR_WECHAT_INFO_BINDED_NO',18002);
define('ERR_WECHAT_INFO_BINDED_MSG','该微信号已绑定');

define('ERR_WECHAT_MOBILE_NOT_EXISTS_NO',18003);
define('ERR_WECHAT_MOBILE_NOT_EXISTS_MSG','该手机号还未注册聚车金融账户，请先注册');

define('ERR_WECHAT_MOBILE_BINDED_NO',18004);
define('ERR_WECHAT_MOBILE_BINDED_MSG','该手机已绑定微信号');

define('ERR_WECHAT_BIND_SUCCESS_NO',18005);
define('ERR_WECHAT_BIND_SUCCESS_MSG','绑定微信账号成功');

define('ERR_WECHAT_BIND_FAIL_NO',18006);
define('ERR_WECHAT_BIND_FAIL_MSG','绑定微信账号失败');

define('ERR_WECHAT_PASSWORD_ERROR_NO',18007);
define('ERR_WECHAT_PASSWORD_ERROR_MSG','登陆密码错误');

define('ERR_WECHAT_REG_BIND_SUCCESS_NO',18008);
define('ERR_WECHAT_REG_BIND_SUCCESS_MSG','注册并绑定微信账号成功');

//用户反馈
define('ERR_FEEDBACK_NOT_EXISTS_NO',19001);
define('ERR_FEEDBACK_NOT_EXISTS_MSG','反馈不存在');

//用户银行卡
define('ERR_USERBANK_NOT_EXISTS_NO',20001);
define('ERR_USERBANK_NOT_EXISTS_MSG','银行卡不存在');

define('ERR_USERBANK_EXISTS_NO',20002);
define('ERR_USERBANK_EXISTS_MSG','银行卡已存在');

define('ERR_USERBANK_DELETE_LOG_ERROR_NO',20003);
define('ERR_USERBANK_DELETE_LOG_ERROR_NO','银行卡删除记录添加失败');

define('ERR_USERBANK_NOT_BIND_NO',20004);
define('ERR_USERBANK_NOT_BIND_MSG','原银行卡尚未绑定完成');

define('ERR_CHECK_STATUS_ERROR_NO',20005);
define('ERR_CHECK_STATUS_ERROR_MSG','设置审核状态错误');

define('ERR_CHECK_STATUS_PROCESSING_NO',20006);
define('ERR_CHECK_STATUS_PROCESSING_MSG','您仍有银行卡修改正在审核中');

define('ERR_USERBANK_MODIFY_LOG_NOT_EXISTS_NO',20007);
define('ERR_USERBANK_MODIFY_LOG_NOT_EXISTS_MSG','银行卡记录修改不存在');

define('ERR_USERBANK_MODIFY_LOG_EXISTS_NO',20008);
define('ERR_USERBANK_MODIFY_LOG_EXISTS_MSG','请勿重复审核');

define('ERR_UNCHECK_CASH_EXISTS_NO',20009);
define('ERR_UNCHECK_CASH_EXISTS_MSG','存在待审核提现，无法修改');

define('ERR_USERBANK_MODIFY_PIC_NOT_EXISTS_NO',20010);
define('ERR_USERBANK_MODIFY_PIC_NOT_EXISTS_MSG','图片还未上传完成，请稍后提交');

//破十亿活动
define('ERR_COUNT_ERROR_NO',21001);
define('ERR_COUNT_ERROR_MSG','发送祝福次数过多');

define('ERR_ACTIVITY_NOT_START_NO',21002);
define('ERR_ACTIVITY_NOT_START_MSG','活动于5月20日 00:00开放，敬请期待');

//存管
define('ERR_BA_ACCOUNT_NOT_OPENED_NO',22001);
define('ERR_BA_ACCOUNT_NOT_OPENED_MSG','未开立存管账户');

define('ERR_BA_ACCOUNT_OPEN_ERROR_NO',22002);
define('ERR_BA_ACCOUNT_OPEN_ERROR_MSG','开立存管账户失败，请稍后再试');

define('ERR_ACOOUNT_PASSWORD_HAS_SET_NO',22003);
define('ERR_ACOOUNT_PASSWORD_HAS_SET_MSG','已经设置过密码');

define('ERR_BA_AUTO_BID_NOT_SET_NO',22004);
define('ERR_BA_AUTO_BID_NOT_SET_MSG','未开通自动投资');

define('ERR_BA_AUTO_BID_HAS_SET_NO',22005);
define('ERR_BA_AUTO_BID_HAS_SET_MSG','已开通自动投资');

define('ERR_BA_CARD_NOT_BIND_NO',22006);
define('ERR_BA_CARD_NOT_BIND_MSG','银行卡未绑定');

define('ERR_BA_CARD_HAS_BIND_NO',22007);
define('ERR_BA_CARD_HAS_BIND_MSG','请解绑后再绑定新银行卡');

define('ERR_ACCOUNT_LOG_TYPE_NO',22008);
define('ERR_ACCOUNT_LOG_TYPE_MSG','资金记录类型错误');

define('ERR_CARD_BANK_CNAPS_NO',22009);
define('ERR_CARD_BANK_CNAPS_MSG','联行号错误');

define('ERR_CASH_TOO_FAST_NO',22010);
define('ERR_CASH_TOO_FAST_MSG','提现频率过快');

define('ERR_CASH_FAILED_NO',22011);
define('ERR_CASH_FAILED_MSG','提现失败');

define('ERR_CASH_NOT_EXISTS_NO',22012);
define('ERR_CASH_NOT_EXISTS_MSG','提现记录不存在');

define('ERR_CASH_CONTROL_NO',22013);
define('ERR_CASH_CONTROL_MSG','该账户已禁止提现，请联系客服');


//banner
define('ERR_BANNER_NOT_EXISTS_NO',23001);
define('ERR_BANNER_NOT_EXISTS_MSG','banner不存在');

//风险测评
define('ERR_RISK_TEST_TIMES_NO',24001);
define('ERR_RISK_TEST_TIMES_MSG','风险测评次数超过限制');

//站内信
define('ERR_MESSAGE_TEXT_NOT_EXISTS_NO',25001);
define('ERR_MESSAGE_TEXT_NOT_EXISTS_MSG','站内信内容不存在');

/* End of file config.php */
/* Location: ./application/config/config.php */
 
